In [1]:
#BASIC-KNN
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  
  
#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
 
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  
  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)

#Predicting the test set result  
y_pred= classifier.predict(x_test)


#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#data frame
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

[[64  4]
 [ 3 29]]
Accuracy :  0.93
    Y_test  Y_pred
0        0       0
1        0       0
2        0       0
3        0       0
4        0       0
..     ...     ...
95       1       0
96       0       0
97       1       1
98       1       1
99       1       1

[100 rows x 2 columns]


In [5]:
# use of KFold and cross validation score on KNN
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  

#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
  
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf.get_n_splits(x,y)
print(kf)

for train_index, test_index in kf.split(x,y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, x_train, y_train, cv=5).mean()
print("Cross Value Score of train set",scores)
score = cross_val_score(classifier, x_test, y_test, cv=5).mean()
print("Cross Value Score of test set",score)

y_pred= classifier.predict(x_test)

#confusing matrix
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#dataframe
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

KFold(n_splits=4, random_state=None, shuffle=False)
Cross Value Score of train set 0.8633333333333333
Cross Value Score of test set 0.96
Confusion Matrix
[[37  1]
 [12 50]]
Accuracy :  0.87
    Y_test  Y_pred
0        1       1
1        1       0
2        1       1
3        1       0
4        0       0
..     ...     ...
95       1       0
96       1       1
97       1       1
98       0       0
99       1       1

[100 rows x 2 columns]


In [6]:
# regression using KFold on SVR
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')

x= data_set.iloc[:,[2,3]].values  
y= data_set.iloc[:, 4].values 

from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf.get_n_splits(x,y)
print(kf)

for train_index, test_index in kf.split(x,y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

from sklearn.svm import SVR 
regressor = SVR()  
regressor.fit(x_train, y_train)  

y_pred = regressor.predict(x_test)

df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', nm.sqrt(metrics.mean_squared_error(y_test, y_pred)))

KFold(n_splits=4, random_state=None, shuffle=False)
    Y_test    Y_pred
0        1  0.082347
1        1  0.015811
2        1  0.988521
3        1  0.061933
4        0 -0.011352
..     ...       ...
95       1  0.070787
96       1  0.101274
97       1  0.097213
98       0  0.096291
99       1  0.088788

[100 rows x 2 columns]
Mean Absolute Error: 0.43533195319406454
Mean Squared Error: 0.37067820370243454
Root Mean Squared Error: 0.6088334778101764


In [8]:
# Bagging classifer of ensemble learning on KNN
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  
  
#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values 

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
from sklearn.ensemble import BaggingClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier1=BaggingClassifier(classifier)
classifier1.fit(x_train, y_train) 

#Predicting the test set result  
y_pred= classifier1.predict(x_test)

#confusing matrix
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#dataframe
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

Confusion Matrix
[[64  4]
 [ 3 29]]
Accuracy :  0.93
    Y_test  Y_pred
0        0       0
1        0       0
2        0       0
3        0       0
4        0       0
..     ...     ...
95       1       0
96       0       0
97       1       1
98       1       1
99       1       1

[100 rows x 2 columns]


In [9]:
# BAGGING CLASSIFIER: use of KFold and cross validation score on KNN
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  

#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
  
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf.get_n_splits(x,y)
print(kf)

for train_index, test_index in kf.split(x,y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.ensemble import BaggingClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier1=BaggingClassifier(classifier)
classifier1.fit(x_train, y_train)  


from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier1, x_train, y_train, cv=5).mean()
print("Cross Value Score of train set",scores)
score = cross_val_score(classifier1, x_test, y_test, cv=5).mean()
print("Cross Value Score of test set",score)

y_pred= classifier1.predict(x_test)

#confusing matrix
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#dataframe
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

KFold(n_splits=4, random_state=None, shuffle=False)
Cross Value Score of train set 0.85
Cross Value Score of test set 0.95
Confusion Matrix
[[37  1]
 [12 50]]
Accuracy :  0.87
    Y_test  Y_pred
0        1       1
1        1       0
2        1       1
3        1       0
4        0       0
..     ...     ...
95       1       1
96       1       1
97       1       1
98       0       0
99       1       1

[100 rows x 2 columns]


In [10]:
# BOASTING CLASSIFIER: use of KFold and cross validation score on KNN
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  

#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
  
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf.get_n_splits(x,y)
print(kf)

for train_index, test_index in kf.split(x,y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.ensemble import AdaBoostClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
AdaBoost = AdaBoostClassifier(n_estimators=100)
AdaBoost.fit(x_train, y_train)  

y_pred= AdaBoost.predict(x_test)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier1, x_train, y_train, cv=5).mean()
print("Cross Value Score of train set",scores)
score = cross_val_score(classifier1, x_test, y_test, cv=5).mean()
print("Cross Value Score of test set",score)

#confusing matrix
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#dataframe
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

KFold(n_splits=4, random_state=None, shuffle=False)
Cross Value Score of train set 0.8533333333333333
Cross Value Score of test set 0.96
Confusion Matrix
[[36  2]
 [15 47]]
Accuracy :  0.83
    Y_test  Y_pred
0        1       1
1        1       1
2        1       1
3        1       0
4        0       0
..     ...     ...
95       1       0
96       1       1
97       1       1
98       0       0
99       1       1

[100 rows x 2 columns]


In [11]:
# BOASTING CLASSIFIER: use of KFold and cross validation score on KNN using pipeline
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('user_data.csv')  

#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
  
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
kf.get_n_splits(x,y)
print(kf)

for train_index, test_index in kf.split(x,y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.ensemble import StackingClassifier
from sklearn.pipeline import make_pipeline 

estimators = [('knn', make_pipeline(StandardScaler(),KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )))]
Stacking = StackingClassifier(estimators=estimators, final_estimator=KNeighborsClassifier())
Stacking.fit(x_train, y_train)  

y_pred=Stacking.predict(x_test)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier1, x_train, y_train, cv=5).mean()
print("Cross Value Score of train set",scores)
score = cross_val_score(classifier1, x_test, y_test, cv=5).mean()
print("Cross Value Score of test set",score)

#confusing matrix
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

#accuracy
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))

#dataframe
df=pd.DataFrame({'Y_test':y_test, 'Y_pred':y_pred})
print(df)

KFold(n_splits=4, random_state=None, shuffle=False)
Cross Value Score of train set 0.8733333333333334
Cross Value Score of test set 0.95
Confusion Matrix
[[28 10]
 [ 8 54]]
Accuracy :  0.82
    Y_test  Y_pred
0        1       1
1        1       1
2        1       1
3        1       1
4        0       0
..     ...     ...
95       1       1
96       1       1
97       1       1
98       0       0
99       1       1

[100 rows x 2 columns]
